### ISSUE TITLE
p5.Part loop playback and regularity

### ISSUE THREAD

**Issue by pitrackster** [therewasaguy/p5.sound#27]
Hi there!

First of all thanks for the work on this library !
I'm trying to develop a metronome using a p5.Part and Phrase and looping the p5.Part playback.

Unfortunately this is not working very well since for a given tempo, the delta between two "tics" is not always the same (with a maximum of 57ms gap @120 BPM on Chrome and 130ms in Firefox).

I'm using a light-weighted wav file (17Ko), Firefox (34.0.5) and Chrome (39.0.***).

Any idea ?
Thanks.
Patrick

**Comment by therewasaguy** [comment]
Hey Patrick,

Thanks for bringing this up!

I just pushed an improvement where Part will return time, in secondsFromNow, for every tick, and will pass that as the second parameter to the Phrase's callback function. The trick is to use this time to schedule your playback. Here's an [example](https://github.com/therewasaguy/p5.sound/blob/2f08158d3be7cc75076b48278772e2110fb1a7f0/examples/looper_simple/sketch.js#L42).

Precision is still an issue. It's most noticeable on start, and changing tabs. There are still occasional gaps during playback, but with this fix they should mostly be under 10ms.

So I'd like to create tests for this and see if there might be a more precise solution.

I've tried a few methods for musical timing in p5.sound. The current method uses a Tone.Clock, which keeps ticks with a square wave oscillator. I think that is super cool, but unfortunately Firefox does not—I only recently got the current method working in Firefox for the latest version of the library. And unfortunately Firefox is likely to have perceptible gaps. 

Originally I had tried this method:
http://www.html5rocks.com/en/tutorials/audio/scheduling. It was reliant on a window.setTimeout with a variable lookahead. The ideal lookahead varied depending on the situation—different browsers, audio buffer sizes, whatever was going on in the main thread. It was too unpredictable, and I didn't want to concern users with setting a custom lookahead time.

But today I discovered that the tutorial's example has been updated to utilize a [Web Worker](https://github.com/cwilso/metronome/blob/master/js/metronomeworker.js) that runs in a separate thread. So far, it seems much more reliable across browsers, even when switching tabs. The trick would be figuring out how to include the worker as an inline blob instead of a separate worker file.

**Comment by pitrackster** [comment]
Hey you're awesome !

I've tried the  [updated web worker solution] (http://webaudiodemos.appspot.com/metronome/), but unfortunately it is still not very accurate...

I'll try your example as soon as I can and let you know if it resolves my problem !
Anyway thanks a lot for your rapid answering

**Comment by pitrackster** [comment]
Your example seems to work perfectly with very little variations ! Thanks a lot !

**Comment by therewasaguy** [comment]
@pitrackster Thanks for the update. I'm planning a fix for SoundFile scheduling, and better scheduling for Filter parameters as well.

Are you still testing in Firefox and Chrome? Is sound crappy in both with the env.play approach?

**Comment by pitrackster** [comment]
Hi !
Great news !
I've seen this library that could help... or not, but just in case : https://github.com/sebpiq/WAAClock

To answer your question, yes I'm testing on both, Firefox and Chrome (linux) and yes it sounds strange (crappy was a bit too much to describe the problem), on both with the env.play approach.
If you want to hear it you can clone the project on my repository (sound files are included) : 

https://github.com/pitrackster/pi-metronome

**Comment by therewasaguy** [comment]
Hi @pitrackster I've updated the SoundFile spec to allow for more precise scheduling
http://p5js.org/reference/#/p5.SoundFile/play

I'll close this issue for now but let me know if you run into any more issues with scheduling.

I think the playback sounds strange because you were looping the soundfile, and it was such a short file. It'd be great if env.play(soundfile) could trigger a sound if it's not already looping, but for now that's not implemented. So I'd suggest getting rid of the envelope for the soundfile, and—if you ever need envelopes on a soundfile—you can schedule your own envelopes with a couple [SoundFile.setVolume()](http://p5js.org/reference/#/p5.SoundFile/setVolume) methods as part of your playTic function.
